# FROM php:8.2-fpm
# FROM php:7.4.33-fpm-buster
# untuk Laravel Framework 8.83.27
FROM php:8.0-fpm-buster

COPY php.ini /usr/local/etc/php/
COPY docker.conf /usr/local/etc/php-fpm.d/docker.conf
COPY .bashrc /root/

# Instal dependensi yang diperlukan oleh Laravel
RUN apt-get update \
    && apt-get install -y \
        libonig-dev \
        libzip-dev \
        unzip \
        curl \
        git \
        libpng-dev \
        libjpeg-dev \
        libfreetype6-dev \
        libwebp-dev \
        libxml2-dev \
        libicu-dev \
        libpq-dev

# Instal ekstensi PHP yang diperlukan oleh Laravel
RUN docker-php-ext-install \
        pdo_mysql \
        zip \
        gd \
        bcmath \
        intl \
        opcache

# Instal Node.js dan npm
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y nodejs

# Instal Composer
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV COMPOSER_HOME /composer
ENV PATH $PATH:/composer/vendor/bin
# RUN composer config --global process-timeout 3600
RUN composer global require "laravel/installer"
RUN composer update
RUN composer require filament/filament:"^2.0"

WORKDIR /root
RUN git clone https://github.com/seebi/dircolors-solarized

EXPOSE 5173
WORKDIR /var/www
