version: '3'

networks:
  network_bi_rag_tiara:
    driver: bridge

services:
  php:
    container_name: php
    build: .docker/php
    ports:
      - 5173:5173
    volumes:
      - .././:/var/www:cached
    networks:
      - network_bi_rag_tiara

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8881:80
    volumes:
      - .././:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - network_bi_rag_tiara

  dbms:
    container_name: dbms_bi_rag_tiara
    image: mysql:8.1
    ports:
      - 3306:3306
    volumes:
      - .docker/db/data:/var/lib/mysql
      - .docker/db/logs:/var/log/mysql
      - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - .docker/db/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=bi_rag_tiara
      - MYSQL_ROOT_PASSWORD=raisa_isyana
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=root
    networks:
      - network_bi_rag_tiara